name : "MicroTodo App Infra"

on:
  push:
   branch:
   - main
     
permission:
  id_token: write
  content: read

jobs:
  terraform-init-plan
  runs_on:MyRunner

  # steps:
  # - name: Checkout
  #   uses: actions/checkout@v6.0.0
